### ISSUE TITLE
Unable to Upload File

### ISSUE THREAD

**Issue by HariBabu-Penumuchi** [SenseNet/sn-client-dotnet#13]
Hi,

I'm trying to upload file to Sensent (Local Machine Instance) through Sensenet .Net Client. But while calling the method 

return await UploadInternalAsync(binaryStream, uploadData, requestData, server, progressCallback);
getting issue like assembly reference not found,
'Could not load file or assembly 'SenseNet.Tools, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'

Could you please help me to resolve this issue. Because the assembly 'SenseNet.Tools' is already exists in my project as well as its up to date.

Please find one more issue(http://server/Root/System/SystemPlugins/Portlets/IntraUploadDialog.ascx(80): error CS0103: The name 'BlobStorageConfiguration' does not exist in the current context) I'm facing while trying to upload file from Screen level. Please find the snapshot attached below.
![sensenet_upload_issue](https://user-images.githubusercontent.com/37583196/45031332-2e077f80-b06c-11e8-8fb8-54960397ac30.png)

**Comment by tusmester** [comment]
Thank you for reaching out! About the second issue: there was an API change in the lower layer that we did not follow yet in the upper (WebPages) layer. This is the related issue:
https://github.com/SenseNet/sn-webpages/issues/26

You can resolve this manually, by simply changing the call in line 80 of the _IntraUploadDialog.ascx_ file mentioned above (and also in the issue). The correct configuration value is:

```txt
SenseNet.Configuration.BlobStorage.BinaryChunkSize
```

**Comment by tusmester** [comment]
Can you please check that the assembly versions in the target folder (where your project is compiled) is the latest (dll right click, Properties-->Details tab):
- SenseNet.Tools: 3.1
- SenseNet.Client: 2.0

If this is not the case, please check the _References_ section of your project in VS, because maybe the SenseNet.Tools referenced dll comes from a different location, not the nuget package (if you click on the dll in solution explorer and open the Properties window, you should see the path pointing to the SenseNet.Tools.3.1 nuget package). I'm asking this because VS sometimes picks up these references from different places than one expects.

**Comment by kavics** [comment]
Fixed in SenseNet/sn-webpages#26

**Comment by phbhari** [comment]
Thank you for your quick updates on my issue. 

Regarding API change in Line 80, the change is not reflecting after clean & rebuild the solution. Because I commented the line 80 and placed the change at line 81. Still error message is same. Please guide me is any other area need to be clear the reference.

Regarding Upload through Dotnet Client, Assembly reference issue has been fixed after I placing reference DLL's into my compile folder. And finally getting "The remote server returned an error: (404) Not Found." while upload action. Please find my code snippet attached below and suggest me if I did any wrong in code level.

In code I would like to upload a text file to folder "Test Folder".

Thank you.
![codesnippet](https://user-images.githubusercontent.com/1633066/45075698-99e9f680-b105-11e8-857d-a97c777b6771.png)

**Comment by phbhari** [comment]
Hi,

Any solution for my issue......

**Comment by tusmester** [comment]
These are the possible issues we can think of:

- the /Root/TestFolder does not exist
- it does exist, but the `File` type is not allowed there
- the admin password has changed and the client simply does not have permission for that folder.

It is generally advisable to create containers on a lower level, for example under the site (`/Root/Sites/Default_Site`), if you installed it. If you put a container in the root, at least try to create more advanced containers, like a _workspace_ and a _document library_ under it, because if you create a simple Folder than you'll have to _allow files to be uploaded there_. This 'allowed child type' feature is to prevent users from creating all kinds of content anywhere in the system - but in some cases this may feel too restrictive.

**Comment by kultsar** [comment]
We are closing this issue, hoping that the above answer could help you. Please feel free to reopen this issue or just open a new one if you have further questions.
